language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - jruby-19mode

script: bundle exec rake

before_install:
  - gem update bundler

cache:
  directories:
    - spec/cache
